version: '3'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    environment:
      - PORT=3000
    depends_on:
      - database
  
  nginx: 
    image: nginx:stable-alpine
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  database:
    image: mongo
    volumes:
      - mongo-db:/data/db/dir
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alak
      - MONGO_INITDB_ROOT_PASSWORD=alakpass
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports: 
      - "6379:6379"

volumes:
  mongo-db:
  